name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Migrate production DB
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: joshuaavalon/flyway-action@v1
        with:
          url: jdbc:postgresql://ece-connect-db.postgres.database.azure.com:5432/ECECONNECT
          user:  ${{ secrets.PGUSERNAME }}
          password: ${{ secrets.PGPASSWORD }}
          locations: filesystem:./db/migrations
      - name: Migrate staging DB
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: joshuaavalon/flyway-action@v1
        with:
          url: jdbc:postgresql://ece-connect-db-staging.postgres.database.azure.com:5432/ECECONNECT
          user:  ${{ secrets.PGUSERNAMESTAGING }}
          password: ${{ secrets.PGPASSWORDSTAGING }}
          locations: filesystem:./db/migrations
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_RIVER_02DFEE710 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "/api" # Api source code path - optional
          output_location: "public" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_RIVER_02DFEE710 }}
          action: "close"
